included:
  - Packages/AppModules/Sources
  - Packages/AppModules/Tests
  - miapp
  - WordSearchWidgetExtension

excluded:
  - Packages/AppModules/.build
  - miapp.xcodeproj
  - Docs

disabled_rules:
  - todo

opt_in_rules:
  - empty_count
  - first_where
  - redundant_nil_coalescing
  - sorted_imports

line_length:
  warning: 140
  error: 180
  ignores_comments: true

file_length:
  warning: 600
  error: 900

type_body_length:
  warning: 320
  error: 500

function_body_length:
  warning: 90
  error: 140

identifier_name:
  min_length:
    warning: 1
  excluded:
    - id
    - r
    - c
    - dr
    - dc
    - dx
    - dy
    - x
    - y
    - t

reporter: "xcode"
